### ISSUE TITLE
Repairs normally unrepairable items

### ISSUE THREAD

**Issue by FurkanS1821** [shindouj/AutoRepairBench#3]
Title ^

spark plugs, headlights, interior parts, glass panels etc. should be unrepairable despite the condition. There should be a setting for this.

**Comment by shindouj** [comment]
When using 0.2.0 beta branch (I haven't merged it into master but it's stable enough to do so I guess) the setting `VanillaBenchRules` controls the items repaired. If set to true, which is the default value, it will only repair items that are available in the regular repair benches. If set to false, it will repair everything. See `Handlers/VanillaPartHandler.cs` - it uses the vanilla method for grabbing items. 

So I'm not exactly sure what you mean. Are you sure that despite that setting set to true your unrepairable items get repaired? If so, please attach your config file and game version so I can confirm this whenever I have a few minutes off.

**Comment by FurkanS1821** [comment]
> Are you sure that despite that setting set to true your unrepairable items get repaired?

Exactly. You can see in the config below, `VanillaBenchRules` is `true` and `MinFixCarPartCondition` is `15`, but it seems to ignore repairability and repair anything above 15%.

By the way, how can I open the solution in VS (2022)? Where are the unity/cms .dll files? It seems to have not found any of them.

Exe file version: `2020.3.32.63664`
Game version: `2020.3.32.1243312`
Config File:
```
[Config]
ShouldFixDentBug = false

[Repair]
RepairBindKey = "F7"
ShouldFixItems = true
ShouldFixBodyParts = true
ShouldLatheBrakeDiscs = true
ShouldBalanceWheels = true
ShouldTakeMoney = true
VanillaBenchRules = false
MinFixCarPartCondition = 15
MaxFixCarPartCondition = 99
FixCarPartBlacklist = [ ]
MinFixBodyPartCondition = 15
MaxFixBodyPartCondition = 99
FixBodyPartBlacklist = [ ]

[Scrapping]
ScrappingBindKey = "F8"
ShouldScrapParts = true
ShouldScrapRepairables = false
MinScrapPartCondition = -1
MaxScrapPartCondition = 99

[Upgrade]
UpgradeBindKey = "F9"
ShouldUpgradeParts = true
ShouldTakeScraps = true
```

**Comment by FurkanS1821** [comment]
Nvm I'm stupid 🤦‍♂️ 
Just realized I didn't change the setting. But I was sure I did. If the config resets itself again, I'll let you know.
