### ISSUE TITLE
Hi! Where I can download or get this library CMS.UI.Windows ?

### ISSUE THREAD

**Issue by microup** [shindouj/AutoRepairBench#5]
Hi!

Could you please help me!) I want to upgrade your mod, but I don't know where I can found this library CMS.UI.Windows :-(
Could you please help me found it?!

Thank you very much!

https://github.com/shindouj/AutoRepairBench/blob/56e3fdf17522d7241dcce75bc3210685e2835be9/AutoRepairBench/AutoRepairBench.cs#L1

**Comment by shindouj** [comment]
Hi!

You can't really _find_ that dependency anywhere. What you'd need to do is to use one of the IL2CPP decompilation tools; I can't really go into details because I barely remember them myself.

Would you mind telling me what needs to be updated? Last time I checked (3 months ago?) it worked fine. I could update it myself tomorrow.

**Comment by microup** [comment]
oh, unfortunately :-(

In last version CMS2021 I can't use this mod because, when I run game I can see in Melon log problems with inventory :-( and I wanted to inspected and fixed it... 

and I have idea create new mod for real situation, when users can't buy any car part in shop for old cars.... but it my dreams to create this mod, because I wan to have same real experience when I need to search car parts on barn, auctions or junkyard

Thank you for you answer!)

**Comment by shindouj** [comment]
Sounds like you're using the wrong version of MelonLoader. I've actually made an updated version for the newer MelonLoader versions but at that time all the other mods depended on the old version.

Please follow these instructions:

Requires MelonLoader (version 0.5.7) to function correctly. Follow the instructions on the website to install it before installing this mod.
**Make sure you are using MelonLoader v0.5.7 - versions 0.6 and newer are incompatible!**

**Comment by microup** [comment]
I have done it  and I got interesting situation... when I have used last version MelonLoader 0.6.1 I have had problem with this mod, but when I downloaded 0.5.7 version, several minutes ago I run mod very well :-)

**Comment by shindouj** [comment]
Glad it works for you now! I'll post a version compatible with the newest MelonLoader sometime in the future - although I've checked and the most popular mods are still depending on 0.5.7.

Closing as done.
