### ISSUE TITLE
Doesnt repair all items. 

### ISSUE THREAD

**Issue by jimlim8510** [shindouj/AutoRepairBench#6]
mod only repairs some of the items. Tested on game version 1.0.32 onwards. (after BMW DLC)

**Comment by shindouj** [comment]
Hi there, @jimlim8510 - thanks for reporting the issue. However, you've not given me much to work with. Could you perhaps attach the following things to help me with reproducing the issue on my side:

- the save with confirmed unfixable items;
- the logs;
- your mod config file.

Thanks!

**Comment by shindouj** [comment]
Closed as no feedback was provided in 30 days.
